globla message: Mensaje global para todos los servicios
spring:
  eureka:
    client:
      service-url:
        defaultZone: http//service-registry:8761/eureka  #cambio localhost por service-registry ya que asi se llama mi imagen del contenedor docker compose
  management:  #habilito actuator que brinda info de cada servicio
    info:
      env:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info
