version: "3.9"  # optional since v1.27.0
services:

  service-registry:
    image: service-registry
    ports:
      - "8761:8761"
    restart: always
  config-service:
    image: config-service
    ports:
      - "8888:8888"
    restart: always
  gateway-service:
    image: gateway-service
    ports:
      - "8080:8080"
    restart: always
  movie-service:
    image: movie-service
    ports:
      - "8882:8882"
    restart: always
  mysql:
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_DATABASE=tp_final
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
